"""Trigger entities."""
from . import *


res('trigger_active_weapon_detect')
res('trigger_add_tf_player_condition')
res('trigger_apply_impulse')
res('trigger_asw_button_area')
res('trigger_asw_chance')
res('trigger_asw_computer_area')
res('trigger_asw_door_area')
res('trigger_asw_jump')
res('trigger_asw_marine_knockback')
res('trigger_asw_marine_position')
res('trigger_asw_random_target')
res('trigger_asw_supplies_chatter')
res('trigger_asw_synup_chatter')
res('trigger_auto_crouch')
res('trigger_autosave')
res('trigger_bomb_reset')
res('trigger_bot_tag')
res('trigger_capture_area')
res('trigger_catapult')
res('trigger_changelevel')
res('trigger_escape')
res('trigger_fall')
res('trigger_finale')
res('trigger_finale_dlc3')
res('trigger_ignite')
res('trigger_ignite_arrows')
res('trigger_impact')
res('trigger_look')
res('trigger_multiple')
res('trigger_once')
res('trigger_paint_cleanser')
res('trigger_passtime_ball')
res('trigger_ping_detector')
res('trigger_player_respawn_override')
res('trigger_playermovement')
res('trigger_playerteam')

res('trigger_portal_button')

res('trigger_proximity')
res('trigger_rd_vault_trigger')
res('trigger_remove')
res('trigger_remove_tf_player_condition')
res('trigger_rpgfire')
res('trigger_serverragdoll')
res('trigger_soundoperator')
res('trigger_standoff')
res('trigger_timer_door')
res('trigger_togglesave')
res('trigger_tonemap')
res('trigger_transition')
res('trigger_upgrade_laser_sight')
res('trigger_vphysics_motion')
res('trigger_weapon_dissolve')
res('trigger_weapon_strip')
res('trigger_wind')
