"""All the weapon pickups.

Weapons are unusual, they don't directly specify the models.
Instead, it's specified in the weapon script.
TODO: Parse weapon scripts!
"""
from . import *


res('weapon_357')
# res('weapon_adrenaline_spawn')
# res('weapon_ak47')
res('weapon_alyxgun')
# res('weapon_ammo_spawn')
res('weapon_annabelle')
res('weapon_ar2')
# res('weapon_aug')
# res('weapon_autoshotgun_spawn')
# res('weapon_awp')
# res('weapon_bizon')
res('weapon_bugbait')
# res('weapon_c4')
# res('weapon_chainsaw_spawn')
res('weapon_citizenpackage')
res('weapon_citizensuitcase')
res('weapon_crossbow')
res('weapon_crowbar')
res('weapon_cubemap')
# res('weapon_cz75a')
# res('weapon_deagle')
# res('weapon_decoy')
# res('weapon_defibrillator_spawn')
# res('weapon_elite')
# res('weapon_famas')
# res('weapon_first_aid_kit')
# res('weapon_first_aid_kit_spawn')
# res('weapon_fiveseven')
# res('weapon_flashbang')
res('weapon_frag')
# res('weapon_g3sg1')
# res('weapon_galilar')
# res('weapon_gascan_spawn')
# res('weapon_glock')
# res('weapon_grenade_launcher')
# res('weapon_grenade_launcher_spawn')
# res('weapon_healthshot')
# res('weapon_hegrenade')
res('weapon_hopwire')
# res('weapon_hkp2000')
# res('weapon_hunting_rifle_spawn')
# res('weapon_incgrenade')
# res('weapon_item_spawn')
# res('weapon_knife')
# res('weapon_m249')
# res('weapon_m4a1')
# res('weapon_m4a1_silencer')
# res('weapon_mac10')
# res('weapon_mag7')
# res('weapon_melee_spawn')
# res('weapon_molotov')
# res('weapon_molotov_spawn')
# res('weapon_mp7')
# res('weapon_mp9')
# res('weapon_negev')
# res('weapon_nova')
# res('weapon_p250')
# res('weapon_p90')
# res('weapon_pain_pills_spawn')
res('weapon_physcannon')
# res('weapon_pipe_bomb_spawn')
res('weapon_pistol')
# res('weapon_pistol_magnum_spawn')
# res('weapon_pistol_spawn')
# res('weapon_portalgun')
# res('weapon_pumpshotgun_spawn')
# res('weapon_revolver')
# res('weapon_rifle_ak47_spawn')
# res('weapon_rifle_desert_spawn')
# res('weapon_rifle_m60_spawn')
# res('weapon_rifle_spawn')
res('weapon_rpg')
# res('weapon_sawedoff')
# res('weapon_scar20')
# res('weapon_scavenge_item_spawn')
# res('weapon_sg556')
res('weapon_shotgun')
# res('weapon_shotgun_chrome_spawn')
# res('weapon_shotgun_spas_spawn')
res('weapon_smg1')
# res('weapon_smg_silenced_spawn')
# res('weapon_smg_spawn')
# res('weapon_smokegrenade')
# res('weapon_sniper_military_spawn')
# res('weapon_spawn')
# res('weapon_ssg08')
# res('weapon_tagrenade')
# res('weapon_taser')
# res('weapon_tec9')
# res('weapon_ump45')
