"""Filter entities."""
from srctools._class_resources import res


res('filter_activator_class')
res('filter_activator_classify')
res('filter_activator_context')
res('filter_activator_flag')
res('filter_activator_hintgroup')
res('filter_activator_infected_class')
res('filter_activator_involume')
res('filter_activator_keyfield')
res('filter_activator_mass_greater')
res('filter_activator_model')
res('filter_activator_name')
res('filter_activator_relationship')
res('filter_activator_squad')
res('filter_activator_surfacedata')
res('filter_activator_team')
res('filter_activator_tfteam')
res('filter_damage_class')
res('filter_base')
res('filter_blood_control')
res('filter_combineball_type')
res('filter_damage_mod')
res('filter_damage_transfer')
res('filter_damage_type')
res('filter_enemy')
res('filter_health')
res('filter_melee_damage')
res('filter_multi')
res('filter_player_held')
res('filter_redirect_inflictor')
res('filter_redirect_owner')
res('filter_redirect_weapon')
res('filter_tf_bot_has_tag')
res('filter_tf_class')
res('filter_tf_condition')
res('filter_tf_damaged_by_weapon_in_slot')
res('filter_tf_player_can_cap')
